services:
  - type: web
    name: studently
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: studently-db
          property: connectionString
      - key: GEMINI_API_KEY
        sync: false
      - key: SESSION_SECRET
        generateValue: true
      - key: NODE_ENV
        value: production

databases:
  - name: studently-db
    databaseName: studently
    user: studently
